theme: cayman
title: "GitHub für Nicht-Programmierer"
description: "Die kostenlose Lernreise für alle, die nicht programmieren."
baseurl: "/github-fuer-nicht-programmierer"
url: "https://planck-lab.github.io"
exclude:
  - docs/
  - LICENSE
  - README.md
